import type { Guide } from "@/lib/content";

export const extraGuides: Guide[] = [
  {
    slug: "slots-guide",
    title: "How to browse slots",
    excerpt: "Use the public slot covers, then read the paytable inside the lobby before you spin.",
    category: "Slots",
    updatedAt: "2026-09-26",
    steps: [
      "Open the slots category and scan the covers. The names under the art are the catalog titles.",
      "Pragmatic Play and Lucky365 are the studios with covers on this site.",
      "Search the games page if you already know the title.",
      "Sign in and open the game. The stake range and paytable are on that screen, not on this website.",
      "If a promotion names eligible slots, follow that card. This guide does not restate bonus values.",
    ],
    related: [
      { href: "/games/slots", label: "Slots" },
      { href: "/games", label: "All games" },
      { href: "/promotions", label: "Promotions" },
    ],
  },
  {
    slug: "live-casino-guide",
    title: "How live tables work",
    excerpt: "Live covers are Evolution and Playtech titles. Limits and the current round are on the table.",
    category: "Live Casino",
    updatedAt: "2026-09-26",
    steps: [
      "Open live casino and choose a cover such as baccarat, roulette, or sic bo.",
      "Sign in before you expect to place a stake.",
      "Read the table limits. They are not copied onto this website.",
      "VIP Baccarat is a Playtech table. Membership VIP is a different label.",
      "Leave the table when the session stops being the stake you planned.",
    ],
    related: [
      { href: "/games/live-casino", label: "Live casino" },
      { href: "/vip", label: "VIP" },
      { href: "/guides/how-to-login", label: "How to login" },
    ],
  },
  {
    slug: "sports-guide",
    title: "How to read the sportsbook",
    excerpt: "Horse racing has a cover. Football is named. Odds stay in the lobby.",
    category: "Sports",
    updatedAt: "2026-09-26",
    steps: [
      "Open sports to see live horse racing artwork from the catalog.",
      "Football is described with the World Cup and the Premier League. Fixtures are not listed here.",
      "Sign in and read the market the sportsbook is offering that day.",
      "Do not treat a number from a chat or a screenshot as the current price.",
      "Esports is a separate category beside the sportsbook.",
    ],
    related: [
      { href: "/games/sports", label: "Sports" },
      { href: "/games/esports", label: "Esports" },
      { href: "/responsible-gaming", label: "Responsible gaming" },
    ],
  },
  {
    slug: "lottery-guide",
    title: "How 4D selection works",
    excerpt: "Magnum, Da Ma Cai, Toto, and Singapore are the named 4D games. Results are not reprinted here.",
    category: "Lottery",
    updatedAt: "2026-09-26",
    steps: [
      "Open lottery and choose one of the four named games.",
      "Enter the digits on the lobby screen. This website does not store a slip.",
      "Check the draw time on that screen. It is not published as a timetable here.",
      "Keep the bet confirmation inside the account if you need to ask support about it.",
      "Do not use a sea-themed slot or a live game show as a substitute for 4D.",
    ],
    related: [
      { href: "/games/lottery", label: "4D lottery" },
      { href: "/guides/how-to-register", label: "How to register" },
      { href: "/games", label: "All games" },
    ],
  },
  {
    slug: "fishing-guide",
    title: "How to open fishing games",
    excerpt: "Fishing has no public covers. The list opens after you sign in.",
    category: "Fishing",
    updatedAt: "2026-09-26",
    steps: [
      "Do not pick Great Blue or Dolphin Reef for fishing. Those are slots.",
      "Sign in and open the fishing category in the lobby.",
      "Read the stake on that game before you play.",
      "Use mobile web or the download path if you are on a phone.",
    ],
    related: [
      { href: "/games/fishing", label: "Fishing" },
      { href: "/games/slots", label: "Slots" },
      { href: "/download", label: "Download" },
    ],
  },
  {
    slug: "esports-guide",
    title: "How to find esports markets",
    excerpt: "Esports is offered with the sportsbook. This site does not print matches or odds.",
    category: "Esports",
    updatedAt: "2026-09-26",
    steps: [
      "Open the esports category to confirm it is separate from horse racing.",
      "Sign in and use the sportsbook area for the markets that are open.",
      "Read the market name and whether betting is still open on that screen.",
      "If you wanted football or racing, use the sports page instead.",
    ],
    related: [
      { href: "/games/esports", label: "Esports" },
      { href: "/games/sports", label: "Sports" },
      { href: "/guides/sports-guide", label: "Sports guide" },
    ],
  },
  {
    slug: "promotions-guide",
    title: "How to read a promotion",
    excerpt: "Campaign names are published. Amounts, turnover, and dates belong on the account card.",
    category: "Promotions",
    updatedAt: "2026-09-26",
    steps: [
      "Read the promotion title on this site, then open the matching card in your account.",
      "Check the product list, any turnover, and the eligibility note on that card.",
      "Do not treat an older public window as a current percentage. Closed windows stay closed.",
      "Opt in only after the card shows the terms you are accepting.",
      "Ask support if the card mentions a step this website does not describe.",
    ],
    related: [
      { href: "/promotions", label: "Promotions" },
      { href: "/guides/deposit-guide", label: "Deposit guide" },
      { href: "/guides/account-guide", label: "Account guide" },
    ],
  },
  {
    slug: "responsible-gaming-guide",
    title: "How to keep play in bounds",
    excerpt: "Decide the budget before you deposit. The site does not promise account tools it has not described.",
    category: "Responsible gaming",
    updatedAt: "2026-09-26",
    steps: [
      "Treat play as entertainment and only use money you can lose.",
      "Set the amount before you open the cashier.",
      "Stop when that amount is gone. Do not deposit again to recover it in the same session.",
      "If the lobby offers deposit limits or self-exclusion, those controls are in the account, not on this page.",
      "Message WhatsApp support to ask about account limits, and use a counselling service you trust if play is no longer fun.",
    ],
    related: [
      { href: "/responsible-gaming", label: "Responsible gaming" },
      { href: "/deposit", label: "Deposit" },
      { href: "/contact", label: "Contact" },
    ],
  },
];
