import type { Guide } from "@/lib/content";

export const extraGuides: Guide[] = [
  {
    slug: "slots-guide",
    title: "E9WIN Slots Guide",
    excerpt: "Use the public slot covers, then read the paytable inside the lobby before you spin.",
    category: "Slots",
    updatedAt: "2026-09-26",
    steps: [
      "Open the slots category and scan the covers. The names under the art are the catalog titles.",
      "Pragmatic Play and Lucky365 are the studios with covers on this site.",
      "Search the games page if you already know the title.",
      "Sign in and open the game. The stake range and paytable are on that screen, not on this website.",
      "If a promotion names eligible slots, follow that card. This guide does not restate bonus values.",
    ],
    related: [
      { href: "/games/slots", label: "E9WIN Slots" },
      { href: "/games", label: "E9WIN Games" },
      { href: "/promotions", label: "Promotions" },
    ],
  },
  {
    slug: "live-casino-guide",
    title: "E9WIN Live Casino Guide",
    excerpt: "Live covers are Evolution and Playtech titles. Limits and the current round are on the table.",
    category: "Live Casino",
    updatedAt: "2026-09-26",
    steps: [
      "Open live casino and choose a cover such as baccarat, roulette, or sic bo.",
      "Sign in before you expect to place a stake.",
      "Read the table limits. They are not copied onto this website.",
      "VIP Baccarat is a Playtech table. Membership VIP is a different label.",
      "Leave the table when the session stops being the stake you planned.",
    ],
    related: [
      { href: "/games", label: "Games hub" },
      { href: "/games/live-casino", label: "Live casino" },
      { href: "/vip", label: "VIP" },
      { href: "/guides/how-to-login", label: "How to login" },
    ],
  },
  {
    slug: "sports-guide",
    title: "E9WIN Sports Guide",
    excerpt: "Horse racing has a cover. Football is named. Odds stay in the lobby.",
    category: "Sports",
    updatedAt: "2026-09-26",
    steps: [
      "Open sports to see live horse racing artwork from the catalog.",
      "Football is described with the World Cup and the Premier League. Fixtures are not listed here.",
      "Sign in and read the market the sportsbook is offering that day.",
      "Do not treat a number from a chat or a screenshot as the current price.",
      "Esports is a separate category beside the sportsbook.",
    ],
    related: [
      { href: "/games", label: "Games hub" },
      { href: "/games/sports", label: "Sports" },
      { href: "/games/esports", label: "Esports" },
      { href: "/responsible-gaming", label: "Responsible gaming" },
    ],
  },
  {
    slug: "lottery-guide",
    title: "E9WIN 4D Guide",
    excerpt: "Magnum, Da Ma Cai, Toto, and Singapore are the named 4D games. Results stay on the lobby screen.",
    category: "Lottery",
    updatedAt: "2026-09-26",
    steps: [
      "Open lottery and choose one of the four named games.",
      "Enter the digits on the lobby screen. This website does not store a slip.",
      "Check the draw time on that screen. It is not published as a timetable here.",
      "Keep the bet confirmation inside the account if you need to ask support about it.",
      "Do not use a sea-themed slot or a live game show as a substitute for 4D.",
    ],
    related: [
      { href: "/games/4d", label: "4D lottery" },
      { href: "/guides/how-to-register", label: "How to register" },
      { href: "/games", label: "All games" },
    ],
  },
  {
    slug: "fishing-guide",
    title: "E9WIN Fishing Guide",
    excerpt: "The fishing list opens in the lobby after you sign in.",
    category: "Fishing",
    updatedAt: "2026-09-26",
    steps: [
      "Do not pick Great Blue or Dolphin Reef for fishing. Those are slots.",
      "Sign in and open the fishing category in the lobby.",
      "Read the stake on that game before you play.",
      "Use mobile web or the download path if you are on a phone.",
    ],
    related: [
      { href: "/games", label: "Games hub" },
      { href: "/games/fishing", label: "Fishing" },
      { href: "/games/slots", label: "Slots" },
      { href: "/download", label: "Download" },
    ],
  },
  {
    slug: "esports-guide",
    title: "E9WIN Esports Guide",
    excerpt: "Esports markets sit with the sportsbook and open after you sign in.",
    category: "Esports",
    updatedAt: "2026-09-26",
    steps: [
      "Open the esports category to confirm it is separate from horse racing.",
      "Sign in and use the sportsbook area for the markets that are open.",
      "Read the market name and whether betting is still open on that screen.",
      "If you wanted football or racing, use the sports page instead.",
    ],
    related: [
      { href: "/games", label: "Games hub" },
      { href: "/games/esports", label: "Esports" },
      { href: "/games/sports", label: "Sports" },
      { href: "/guides/sports-guide", label: "E9WIN Sports Guide" },
    ],
  },
  {
    slug: "promotions-guide",
    title: "How to read a promotion",
    excerpt: "Campaign names are published. Amounts, turnover, and dates belong on the account card.",
    category: "Promotions",
    updatedAt: "2026-09-26",
    steps: [
      "Read the promotion title on this site, then open the matching card in your account.",
      "Check the product list, any turnover, and the eligibility note on that card.",
      "Do not treat an older public window as a current percentage. Closed windows stay closed.",
      "Opt in only after the card shows the terms you are accepting.",
      "Ask support if the card mentions a step this website does not describe.",
    ],
    related: [
      { href: "/promotions", label: "Promotions" },
      { href: "/guides/deposit-guide", label: "Deposit guide" },
      { href: "/guides/account-guide", label: "Account guide" },
    ],
  },
  {
    slug: "security-guide",
    title: "E9WIN Security Guide",
    excerpt: "Use one login, install only from the download page, and never send a password to support.",
    category: "Security",
    updatedAt: "2026-09-26",
    steps: [
      "Create one account and keep the username private enough that you can still tell support who you are.",
      "Do not send the password on WhatsApp or Facebook. Support can work from the username.",
      "Install Android only from the portal link on the download page. There is no store listing to trust instead.",
      "Pay only the cashier instruction shown at that moment. A number from a chat is not a deposit account.",
      "Withdraw to a bank or e-wallet in the same name as the profile.",
    ],
    related: [
      { href: "/guides/account-guide", label: "Account guide" },
      { href: "/download", label: "Download" },
      { href: "/contact", label: "Contact" },
    ],
  },
  {
    slug: "responsible-gaming-guide",
    title: "How to keep play in bounds",
    excerpt: "Decide the budget before you deposit. The site does not promise account tools it has not described.",
    category: "Responsible gaming",
    updatedAt: "2026-09-26",
    steps: [
      "Treat play as entertainment and only use money you can lose.",
      "Set the amount before you open the cashier.",
      "Stop when that amount is gone. Do not deposit again to recover it in the same session.",
      "If the lobby offers deposit limits or self-exclusion, those controls are in the account, not on this page.",
      "Message WhatsApp support to ask about account limits, and use a counselling service you trust if play is no longer fun.",
    ],
    related: [
      { href: "/responsible-gaming", label: "Responsible gaming" },
      { href: "/deposit", label: "Deposit" },
      { href: "/contact", label: "Contact" },
    ],
  },
  {
    slug: "how-to-start",
    title: "How to start playing",
    excerpt: "Register, open the lobby, pick a category, and read the stake screen before the first bet.",
    category: "Games",
    updatedAt: "2026-09-27",
    steps: [
      "Create one account with a name that matches the bank or e-wallet you will use later.",
      "Sign in through the player lobby. This website does not keep a session.",
      "Open Games and choose slots, live casino, sports, 4D, fishing, or esports.",
      "Read the paytable, table limits, or market on that screen. This site does not reprint them.",
      "Deposit only after you have decided the amount, using the cashier instruction for that attempt.",
    ],
    related: [
      { href: "/guides/how-to-register", label: "How to register" },
      { href: "/games", label: "Games" },
      { href: "/deposit", label: "Deposit" },
    ],
  },
  {
    slug: "android-guide",
    title: "Android access",
    excerpt: "Open the player portal from the download page. There is no Google Play listing to follow.",
    category: "Download",
    updatedAt: "2026-09-27",
    steps: [
      "On the download page, use the Android action. It opens the player portal.",
      "Install only the file that portal gives you. Do not use an APK from a search result or a chat.",
      "Open the lobby and sign in with the username you registered.",
      "If the portal link fails, message WhatsApp support. Do not switch to another download site.",
    ],
    related: [
      { href: "/download", label: "Download" },
      { href: "/guides/iphone-guide", label: "iPhone access" },
      { href: "/guides/mobile-guide", label: "Mobile guide" },
    ],
  },
  {
    slug: "iphone-guide",
    title: "iPhone access",
    excerpt: "Use Safari, then Add to Home Screen. E9WIN does not publish an App Store listing.",
    category: "Download",
    updatedAt: "2026-09-27",
    steps: [
      "Open the E9WIN site in Safari. Other browsers on iPhone may not offer Add to Home Screen the same way.",
      "Tap Share, then Add to Home Screen, and confirm the icon.",
      "Open the icon and sign in. The shortcut is the web lobby, not a separate app binary.",
      "You can also stay in the Safari tab without adding an icon.",
    ],
    related: [
      { href: "/download", label: "Download" },
      { href: "/guides/android-guide", label: "Android access" },
      { href: "/guides/how-to-login", label: "How to login" },
    ],
  },
  {
    slug: "payment-guide",
    title: "E9WIN Payment Guide",
    excerpt: "Match the cashier method to the account you control, then follow the instruction on that attempt.",
    category: "Payments",
    updatedAt: "2026-09-27",
    steps: [
      "Open the cashier after you sign in. The methods on the public strip are banks, e-wallets, telco PIN, and USDT.",
      "For a bank or e-wallet, use an account in the same name as the profile.",
      "Copy the account, reference, wallet address, or PIN instruction shown for that attempt.",
      "Friend credit moves balance between player accounts. It is not a bank withdrawal.",
      "Keep the receipt until the wallet updates, then use the withdrawal guide when you cash out.",
    ],
    related: [
      { href: "/payment-methods", label: "Payment methods" },
      { href: "/guides/deposit-guide", label: "Deposit guide" },
      { href: "/guides/withdrawal-guide", label: "Withdrawal guide" },
    ],
  },
];
